"use client";

import { useState } from "react";
import {
  AiGeneratedBadge,
  Button,
  Card,
  CardBody,
  CardHeader,
  CardTitle,
  StatusBadge,
} from "@/components/ui/primitives";
import { bloomLabel } from "@/lib/utils";

interface Topic {
  id: string;
  code: string;
  title: string;
  week: number;
}

interface Segment {
  title: string;
  minutes: number;
  bloomLevel: number;
  cloCode: string;
  activityType: string;
  content: string;
  instructorNotes: string;
  citedChunkIds: string[];
}

interface Assertion {
  name: string;
  passed: boolean;
  detail: string;
}

interface PlanResponse {
  plan: {
    title: string;
    framing: string;
    segments: Segment[];
    anticipatedMisconceptions: string[];
  };
  assertions: Assertion[];
  regenerated: boolean;
  warning: string | null;
  model: string;
}

export function LectureClient({ courseId, topics }: { courseId: string; topics: Topic[] }) {
  const [topicId, setTopicId] = useState(topics[0]?.id ?? "");
  const [duration, setDuration] = useState(90);
  const [result, setResult] = useState<PlanResponse | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setBusy(true);
    setError(null);
    setResult(null);

    const res = await fetch("/api/teacher/lecture-plan", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ courseId, topicId, durationMinutes: duration }),
    });

    if (!res.ok) {
      const body = (await res.json().catch(() => null)) as
        | { error?: { message?: string } }
        | null;
      setError(body?.error?.message ?? "Could not generate a plan.");
      setBusy(false);
      return;
    }

    setResult((await res.json()) as PlanResponse);
    setBusy(false);
  }

  function exportMarkdown() {
    if (!result) return;
    const topic = topics.find((t) => t.id === topicId);
    const lines = [
      `# ${result.plan.title}`,
      "",
      `_${topic?.code} ${topic?.title} · generated by ${result.model} · AI-generated, review before use_`,
      "",
      result.plan.framing,
      "",
      ...result.plan.segments.flatMap((s, i) => [
        `## ${i + 1}. ${s.title}`,
        "",
        `**${s.minutes} min · ${s.activityType} · Bloom ${s.bloomLevel} · ${s.cloCode}**`,
        "",
        s.content,
        "",
        `_Instructor notes:_ ${s.instructorNotes}`,
        "",
        s.citedChunkIds.length > 0 ? `_Sources:_ ${s.citedChunkIds.join(", ")}` : "",
        "",
      ]),
    ];

    const blob = new Blob([lines.join("\n")], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `lecture-${topic?.code ?? "plan"}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Session</CardTitle>
        </CardHeader>
        <CardBody className="space-y-4">
          <div className="flex flex-wrap items-end gap-3">
            <div className="space-y-1">
              <label htmlFor="topic" className="block text-sm font-medium">
                Topic
              </label>
              <select
                id="topic"
                value={topicId}
                onChange={(e) => setTopicId(e.target.value)}
                className="rounded-md border border-input bg-background px-3 py-2 text-sm"
              >
                {topics.map((topic) => (
                  <option key={topic.id} value={topic.id}>
                    {topic.code} · {topic.title} (week {topic.week})
                  </option>
                ))}
              </select>
            </div>

            <div className="space-y-1">
              <label htmlFor="duration" className="block text-sm font-medium">
                Duration (minutes)
              </label>
              <input
                id="duration"
                type="number"
                min={20}
                max={240}
                step={5}
                value={duration}
                onChange={(e) => setDuration(Number(e.target.value))}
                className="w-28 rounded-md border border-input bg-background px-3 py-2 text-sm"
              />
            </div>

            <Button onClick={() => void generate()} disabled={busy || !topicId}>
              {busy ? "Planning…" : "Generate plan"}
            </Button>
          </div>

          {error && (
            <p role="alert" className="text-sm text-destructive">
              {error}
            </p>
          )}
        </CardBody>
      </Card>

      {result && (
        <>
          {/*
            Assertions are shown pass or fail: the Bloom-ascending and
            formative-check promises are checked, not just claimed.
          */}
          <Card>
            <CardHeader className="flex flex-wrap items-center justify-between gap-2">
              <CardTitle>Structural checks</CardTitle>
              {result.regenerated && (
                <StatusBadge kind="info" label="regenerated once after a violation" />
              )}
            </CardHeader>
            <CardBody className="space-y-2">
              {result.warning && (
                <p
                  role="alert"
                  className="rounded-md border border-warning/40 bg-warning/10 px-3 py-2 text-sm text-warning"
                >
                  {result.warning}
                </p>
              )}
              <ul className="space-y-1.5">
                {result.assertions.map((assertion) => (
                  <li key={assertion.name} className="flex gap-2 text-xs">
                    <StatusBadge
                      kind={assertion.passed ? "success" : "warning"}
                      label={assertion.name.replace(/_/g, " ")}
                    />
                    <span className="text-muted-foreground">{assertion.detail}</span>
                  </li>
                ))}
              </ul>
            </CardBody>
          </Card>

          <Card>
            <CardHeader className="flex flex-wrap items-center justify-between gap-2">
              <div>
                <CardTitle>{result.plan.title}</CardTitle>
                <p className="mt-0.5 text-xs text-muted-foreground">{result.plan.framing}</p>
              </div>
              <div className="flex items-center gap-2">
                <AiGeneratedBadge />
                <Button variant="secondary" className="text-xs" onClick={exportMarkdown}>
                  Export Markdown
                </Button>
              </div>
            </CardHeader>
            <CardBody>
              <ol className="space-y-4">
                {result.plan.segments.map((segment, index) => (
                  <li key={index} className="border-l-2 border-primary/30 pl-4">
                    <div className="flex flex-wrap items-baseline justify-between gap-2">
                      <h3 className="text-sm font-medium">
                        {index + 1}. {segment.title}
                      </h3>
                      <span className="text-xs text-muted-foreground">
                        {segment.minutes} min · {segment.activityType} · Bloom{" "}
                        {segment.bloomLevel} ({bloomLabel(segment.bloomLevel)}) ·{" "}
                        {segment.cloCode}
                      </span>
                    </div>
                    <p className="mt-1 text-sm">{segment.content}</p>
                    <p className="mt-1 text-xs text-muted-foreground">
                      <span className="font-medium">Instructor notes:</span>{" "}
                      {segment.instructorNotes}
                    </p>
                    {segment.citedChunkIds.length > 0 && (
                      <p className="mt-1 text-xs text-muted-foreground">
                        Sources: {segment.citedChunkIds.length} chunk
                        {segment.citedChunkIds.length === 1 ? "" : "s"}
                      </p>
                    )}
                  </li>
                ))}
              </ol>

              {result.plan.anticipatedMisconceptions.length > 0 && (
                <div className="mt-4 border-t pt-3">
                  <p className="text-xs font-medium">Anticipated misconceptions</p>
                  <ul className="mt-1 list-inside list-disc">
                    {result.plan.anticipatedMisconceptions.map((m) => (
                      <li key={m} className="text-xs text-muted-foreground">
                        {m}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </CardBody>
          </Card>
        </>
      )}
    </div>
  );
}
